//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DvDCollection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public Movy()
        {
            this.Actors = new HashSet<Actor>();
        }
    
        public int MovieID { get; set; }
        public string Title { get; set; }
        public string Rating { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Runtime { get; set; }
        public string Director { get; set; }
    
        public virtual ICollection<Actor> Actors { get; set; }
    }
}
