//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWC_LMS
{
    using System;
    
    public partial class GetTeachersCourseInfo_Result1
    {
        public string CourseName { get; set; }
        public Nullable<int> Students { get; set; }
        public bool IsArchived { get; set; }
        public int CourseId { get; set; }
    }
}
